// NEEO REMOTE BUTTONS
exports.BTN_NEEO_POWER_ON = 'POWER ON';
exports.BTN_NEEO_POWER_OFF = 'POWER OFF';
exports.BTN_NEEO_CURSOR_LEFT = 'CURSOR LEFT';
exports.BTN_NEEO_CURSOR_RIGHT = 'CURSOR RIGHT';
exports.BTN_NEEO_CURSOR_DOWN = 'CURSOR DOWN';
exports.BTN_NEEO_CURSOR_UP = 'CURSOR UP';
exports.BTN_NEEO_CURSOR_ENTER = 'CURSOR ENTER';
exports.BTN_NEEO_MUTE = 'MUTE TOGGLE';
exports.BTN_NEEO_VOLUME_UP = 'VOLUME UP';
exports.BTN_NEEO_VOLUME_DOWN = 'VOLUME DOWN';
exports.BTN_NEEO_CHANNEL_UP = 'CHANNEL UP';
exports.BTN_NEEO_CHANNEL_DOWN = 'CHANNEL DOWN';
exports.BTN_NEEO_MENU = 'MENU';
exports.BTN_NEEO_GUIDE = 'GUIDE';
exports.BTN_NEEO_BACK = 'BACK';
exports.BTN_NEEO_EXIT = 'EXIT';

// NEEO TV BUTTONS
exports.BTN_NEEO_FUNCTION_RED = 'FUNCTION RED';
exports.BTN_NEEO_FUNCTION_GREEN = 'FUNCTION GREEN';
exports.BTN_NEEO_FUNCTION_YELLOW = 'FUNCTION YELLOW';
exports.BTN_NEEO_FUNCTION_BLUE = 'FUNCTION BLUE';
exports.BTN_NEEO_DIGIT_0 = 'DIGIT 0';
exports.BTN_NEEO_DIGIT_1 = 'DIGIT 1';
exports.BTN_NEEO_DIGIT_2 = 'DIGIT 2';
exports.BTN_NEEO_DIGIT_3 = 'DIGIT 3';
exports.BTN_NEEO_DIGIT_4 = 'DIGIT 4';
exports.BTN_NEEO_DIGIT_5 = 'DIGIT 5';
exports.BTN_NEEO_DIGIT_6 = 'DIGIT 6';
exports.BTN_NEEO_DIGIT_7 = 'DIGIT 7';
exports.BTN_NEEO_DIGIT_8 = 'DIGIT 8';
exports.BTN_NEEO_DIGIT_9 = 'DIGIT 9';
exports.BTN_NEEO_INFO = 'INFO';

// BRAVIA BUTTONS
exports.BTN_BRAVIA_INPUT = 'INPUT';
exports.BTN_BRAVIA_INPUT_HDMI1 = 'INPUT HDMI 1';
exports.BTN_BRAVIA_INPUT_HDMI2 = 'INPUT HDMI 2';
exports.BTN_BRAVIA_INPUT_HDMI3 = 'INPUT HDMI 3';
exports.BTN_BRAVIA_INPUT_HDMI4 = 'INPUT HDMI 4';
exports.BTN_BRAVIA_HOME = 'HOME';
exports.BTN_BRAVIA_STOP = 'STOP';
exports.BTN_BRAVIA_ENTER = 'ENTER';
exports.BTN_BRAVIA_PLAY = 'PLAY';
exports.BTN_BRAVIA_PAUSE = 'PAUSE';
exports.BTN_BRAVIA_RECORD = 'RECORD';
exports.BTN_BRAVIA_SKIP_BACKWARD = 'SKIP BACKWARD';
exports.BTN_BRAVIA_SKIP_FORWARD = 'SKIP FORWARD';
exports.BTN_BRAVIA_FORWARD = 'FORWARD';
exports.BTN_BRAVIA_REVERSE = 'REVERSE';
exports.BTN_BRAVIA_INPUT_TV = 'INPUT TV';
exports.BTN_BRAVIA_INPUT_RADIO = 'INPUT RADIO';
exports.BTN_BRAVIA_NETFLIX = 'NETFLIX';
exports.BTN_BRAVIA_GOOGLE_PLAY = 'GOOGLE PLAY';
exports.BTN_BRAVIA_DISNEY = 'DISNEY';